REMOTE_URL = "http://127.0.0.1:4723/wd/hub"
PLATFORM_NAME = "Android"
PLATFORM_VERSION = "13.0"
DEVICE_NAME = "emulator-5554"
Activity_NAME = "com.android.deskclock.DeskClock"
PACKAGE_NAME = "com.google.android.deskclock"

APP_HEADER = "id = com.google.android.deskclock:id/action_bar_title"
ALARM_TAB = "id = com.google.android.deskclock:id/tab_menu_alarm"
TIMER_TAB = "id = com.google.android.deskclock:id/tab_menu_timer"
STOPWATCH_TAB = "id = com.google.android.deskclock:id/tab_menu_stopwatch"
BEDTIME_TAB = "id = com.google.android.deskclock:id/tab_menu_bedtime"
CLOCK_TAB = "id = com.google.android.deskclock:id/tab_menu_clock"
