REMOTE_URL = "http://127.0.0.1:4723/wd/hub"
PLATFORM_NAME = "Android"
PLATFORM_VERSION = "13.0"
DEVICE_NAME = "emulator-5554"
Activity_NAME = "com.android.deskclock.DeskClock"
PACKAGE_NAME = "com.google.android.deskclock"

APP_HEADER = "id = com.google.android.deskclock:id/action_bar_title"
ALARM_TAB = "id = com.google.android.deskclock:id/tab_menu_alarm"
TIMER_TAB = "id = com.google.android.deskclock:id/tab_menu_timer"
STOPWATCH_TAB = "id = com.google.android.deskclock:id/tab_menu_stopwatch"
BEDTIME_TAB = "id = com.google.android.deskclock:id/tab_menu_bedtime"
CLOCK_TAB = "id = com.google.android.deskclock:id/tab_menu_clock"

GET_TIME = "id = com.google.android.deskclock:id/digital_clock"
ADD_CITY = "//android.widget.Button[@content-desc='Add city']"
SEARCH_CITY = "id = com.google.android.deskclock:id/open_search_view_edit_text"
SEARCH_RESULT = "id = com.google.android.deskclock:id/city_name"
CITY_NAME = "id = com.google.android.deskclock:id/city_name"
TIMER_SET = "id = com.google.android.deskclock:id/fab"
TIMER_STOP = "//android.widget.Button[@content-desc='Stop']"
ADD_ALARM = "//android.widget.Button[@content-desc='Add alarm']"
ALARM_HR = "id = com.google.android.deskclock:id/material_hour_tv"
ALARM_MIN = "id = com.google.android.deskclock:id/material_minute_tv"
NEW_ALARM = "//androidx.cardview.widget.CardView[@content-desc=' Alarm'][1]/android.view.ViewGroup"
SET_ALARM = "id = com.google.android.deskclock:id/material_timepicker_ok_button"
